In [1]:
import numpy as np

## 0차원

- numpy array는 1 또는 5, 10와 같이 숫자 데이터를 array화 해줄 수 있음


In [8]:
arr = np.array(5)

arr.shape

()

In [5]:
arr.ndim

0

## 1차원
- 숫자가 10과 같이 하나만 들어간다고 해도 [] 리스트를 한번 씌우게 되면 차원이 생긴다 
- 이때는 1차원이 되는건데 numpy 에서 shape를 표현 할 때 (1)이 아닌 (1, )  이런 식으로 표현하게 됨 
- shape는 앞의수가 가장 바깥에 있는 대괄호에 몇개가 있는지를 말함.

In [6]:
arr = np.array([5])
arr.shape

(1,)

In [7]:
arr.ndim

1

- 1차원에 3개의 값이 들어갔다는 의미

In [12]:
arr = np.array([1,2,3])
print(arr.ndim) #1차원
arr.shape

1


(3,)

## 2차원
- 대괄호를 추가적으로 씌우면 차원이 추가

In [13]:
arr = np.array([[1,2,3]])
print(arr.ndim) #2차원
arr.shape

2


(1, 3)

In [14]:
arr = np.array([[1,2,3],[1,2,3],[1,2,3]])
print(arr.ndim)
arr.shape

2


(3, 3)

In [15]:
arr = np.array([[3]])
print(arr.ndim)
arr.shape

2


(1, 1)

## zeros & ones

In [17]:
zeros = np.zeros([3,3])
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
zeros = np.zeros(3)
zeros

array([0., 0., 0.])

In [23]:
ones = np.ones([1,3])
ones

array([[1., 1., 1.]])

## arrange

In [26]:
arr = np.arange(5)
print(arr)
arr = np.arange(4,9)
print(arr)

[0 1 2 3 4]
[4 5 6 7 8]


In [28]:
arr = np.arange(9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## indexing

In [30]:
print(arr[0,0],arr[1,2])

0 5


In [31]:
print(arr[1])

[3 4 5]


In [32]:
print(arr[1:])

[[3 4 5]
 [6 7 8]]


In [33]:
print(arr[1:,1:]) #1행부터, 1열부터가져와라

[[4 5]
 [7 8]]


In [36]:
print(arr[:,0])

[0 3 6]


## boolean indexing

In [37]:
data = np.random.randn(3,3)
data

array([[-0.14254001, -0.81784535,  0.51149706],
       [ 0.17244813,  0.82074528,  0.50155871],
       [ 0.85417365, -2.00989917, -0.99197971]])

In [38]:
data <= 0

array([[ True,  True, False],
       [False, False, False],
       [False,  True,  True]])

In [41]:
data[data<=0]

array([-0.14254001, -0.81784535, -2.00989917, -0.99197971])

In [42]:
data[data<=0] = 1
data

array([[1.        , 1.        , 0.51149706],
       [0.17244813, 0.82074528, 0.50155871],
       [0.85417365, 1.        , 1.        ]])

## broadcasting

In [43]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [48]:
print(arr+3)
np.add(arr,3)

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [51]:
print(arr*3)
np.multiply(arr,3)

[[ 0  3  6]
 [ 9 12 15]
 [18 21 24]]


array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [50]:
arr + np.array([1,1,1])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
arr_1 = np.random.randint(1,3,size=9).reshape(3,3)
arr_1

array([[2, 1, 2],
       [1, 1, 1],
       [2, 1, 2]])

In [59]:
arr_2 = np.random.randint(1,3,size=27).reshape(3,3,3)
arr_2

array([[[2, 2, 1],
        [1, 1, 1],
        [2, 2, 2]],

       [[2, 2, 1],
        [2, 2, 2],
        [1, 1, 1]],

       [[2, 2, 1],
        [1, 2, 1],
        [1, 2, 2]]])

In [68]:
print(arr_1 + arr_2)       # arr_1이 복사되어 다 더해짐
print((arr_1+arr_2).shape)

[[[4 3 3]
  [2 2 2]
  [4 3 4]]

 [[4 3 3]
  [3 3 3]
  [3 2 3]]

 [[4 3 3]
  [2 3 2]
  [3 3 4]]]
(3, 3, 3)


In [61]:
arr_1 * arr_2

array([[[4, 2, 2],
        [1, 1, 1],
        [4, 2, 4]],

       [[4, 2, 2],
        [2, 2, 2],
        [2, 1, 2]],

       [[4, 2, 2],
        [1, 2, 1],
        [2, 2, 4]]])

In [62]:
np.sum(arr_1)

13

In [63]:
np.max(arr_1)

2

## 차원에 대한 이해

In [69]:
print(arr_1 + arr_2)
print((arr_1+arr_2).shape)

[[[4 3 3]
  [2 2 2]
  [4 3 4]]

 [[4 3 3]
  [3 3 3]
  [3 2 3]]

 [[4 3 3]
  [2 3 2]
  [3 3 4]]]
(3, 3, 3)


In [81]:
arr=arr_1 + arr_2
arr[1,2,1]

2

In [83]:
np.sum(arr_1+arr_2,axis=0)

array([[12,  9,  9],
       [ 7,  8,  7],
       [10,  8, 11]])

4+4+4 = 12 : 0차원 값 더해줌 (0,0,0) + (1,0,0) + (2,0,0)

In [75]:
np.sum(arr_1+arr_2,1) 

array([[10,  8,  9],
       [10,  8,  9],
       [ 9,  9,  9]])

4+2+4 = 10 : 1차원 값 더해줌 (0,0,0) + (0,1,0) + (0,2,0)

In [76]:
np.sum(arr_1+arr_2,2) 

array([[10,  6, 11],
       [10,  9,  8],
       [10,  7, 10]])

4+3+3 = 10 : 2차원 값 더해줌 (0,0,0) + (0,0,1) + (0,0,2)

## argmax
 - 가장 큰 값의 인덱스 반환
 - 앞에서 부터 탐색

In [85]:
np.argmax([1,2,3,3,4,9,9])

5

In [86]:
np.unique([1,2,3,3,4,9,9])

array([1, 2, 3, 4, 9])

## data type
 - array.dtype : 해당 어레이의 최대 데이터 타입 출력
 - array = array.astype('float32' 혹은 np.int32) : 어레이의 타입 변경

In [90]:
arr = np.array([[1,2,3],[4,5,6]])
arr.dtype

dtype('int32')

In [93]:
arr=arr.astype('float32')
arr.dtype

dtype('float32')

In [94]:
arr=arr.astype(np.uint16)
arr.dtype

dtype('uint16')

In [98]:
arr = np.array([[1,2,3],[4,5,6]], dtype=np.uint8)
arr.dtype

dtype('uint8')

## 차원

In [99]:
len(arr.shape)

2

In [100]:
arr.shape

(2, 3)

In [101]:
arr.size # 2*3

6

## reshape
 - size는 같아야 함
 - size가 너무 커서 모를때 -1 하면 다 풀어줌

In [103]:
arr1 = arr.reshape(3,2)
arr1

array([[1, 2],
       [3, 4],
       [5, 6]], dtype=uint8)

In [105]:
arr1 = arr.reshape([6])
arr1

array([1, 2, 3, 4, 5, 6], dtype=uint8)

In [106]:
arr1 = arr.reshape(6)
arr1

array([1, 2, 3, 4, 5, 6], dtype=uint8)

In [107]:
arr1 = arr.reshape(-1)
arr1

array([1, 2, 3, 4, 5, 6], dtype=uint8)

In [110]:
arr1 = arr.reshape(-1,2) #2로 나눈 나머지 자동으로 나줘줌
arr1

array([[1, 2],
       [3, 4],
       [5, 6]], dtype=uint8)

In [109]:
arr1 = arr.reshape(-1,3)
arr1

array([[1, 2, 3],
       [4, 5, 6]], dtype=uint8)

## Ravel
 - 어레이의 차원 원소들을 1차원으로 쭉 펴는거
 - reshape(-1)과 같음

In [112]:
arr1 = arr.ravel()
arr1

array([1, 2, 3, 4, 5, 6], dtype=uint8)

## np.expand_dims()
 - 안의 값은 유지하되 차원 수를 늘릴 때
 - reshape 로 늘리는 거랑 다름

In [113]:
arr1

array([1, 2, 3, 4, 5, 6], dtype=uint8)

In [114]:
arr1.shape

(6,)

In [122]:
arr_e = np.expand_dims(arr1,0)
arr_e.shape

(1, 6)

In [123]:
arr_e = np.expand_dims(arr1,1)
arr_e.shape

(6, 1)

In [124]:
arr2 = np.expand_dims(arr1,-1)
arr2.shape

(6, 1)

In [126]:
arr2 = np.expand_dims(np.expand_dims(arr1,-1),0)
arr2.shape

(1, 6, 1)